id: IE7DD14B9
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:20:24.152211
last_modified: 2023-02-10 00:20:24.152299
source_metadata:
  title: Saṅghabhedavastu
  language: bo
bases:
  81C6:
    base_file: 81C6.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
